server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: interaction-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://interaction-mongo-db:27017/hsmart_interaction_db}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.hsmart.backend: INFO
